window.CUCAS_VEHICLE_BACHELOR = {
  "scrape_date": "2026-09-12",
  "source": "CUCAS (cucas.cn university program pages)",
  "filter": "Bachelor / Undergraduate only",
  "dedupe_key": "university + program_name + language",
  "counts": {
    "bachelor_listings_by_url": 9,
    "unique_programs_after_dedupe": 8,
    "unique_universities": 8,
    "excluded_non_bachelor_discovered": 5
  },
  "programs": [
    {
      "university": "Chang'an University",
      "program_name": "Vehicle Engineering",
      "degree_level": "Bachelor",
      "language": "English",
      "duration": "4 Years",
      "city_province": "Xi'an, Shaanxi",
      "tuition": "RMB 16,000 Per Year",
      "application_deadline": "Jun 20, 2026",
      "starting_date": "Sep 1, 2026",
      "scholarship_notes": "CUCAS notes scholarship service fee USD 200 if converting to scholarship",
      "cucas_url": "https://chd.cucas.cn/program/Vehicle-Engineering-71881.html",
      "keyword_found": "Vehicle Engineering",
      "application_fee": "USD 57",
      "service_fee": "USD 200",
      "special_notes": "CSCA required; IELTS 5.5 / TOEFL IBT 68+; high school graduate; ages 18-50",
      "related_urls": [
        "https://chd.cucas.cn/program/Vehicle-Engineering-71881.html"
      ],
      "intake_notes": "Sep 1, 2026 / deadline Jun 20, 2026"
    },
    {
      "university": "Jiangsu University",
      "program_name": "Vehicle Engineering",
      "degree_level": "Bachelor",
      "language": "English",
      "duration": "4 Years",
      "city_province": "Zhenjiang, Jiangsu",
      "tuition": "RMB 20,000 Per Year",
      "application_deadline": "Jun 30, 2027",
      "starting_date": "Sep 14, 2027",
      "scholarship_notes": "JSU Presidential scholarship pages exist on CUCAS for Vehicle Engineering (Type A/B coverage noted on scholarship listing)",
      "cucas_url": "https://jsu.cucas.cn/program/Vehicle-Engineering-79482.html",
      "keyword_found": "Vehicle Engineering",
      "application_fee": "USD 29",
      "service_fee": "USD 200",
      "special_notes": "Autumn intake; CSCA required; IELTS 5.5+ / TOEFL 80+ / Duolingo 100+; RMB 3,000 deposit before admission letter; ages 18-25 | Multiple CUCAS listings for same uni+program+language (see related_urls)",
      "related_urls": [
        "https://jsu.cucas.cn/program/Vehicle-Engineering-79482.html",
        "https://jsu.cucas.cn/program/Vehicle-Engineering-72919.html"
      ],
      "intake_notes": "Sep 14, 2027 / deadline Jun 30, 2027; ALSO Mar 13, 2027 / deadline Jan 1, 2027 (https://jsu.cucas.cn/program/Vehicle-Engineering-72919.html)"
    },
    {
      "university": "Northeastern University",
      "program_name": "Vehicle Engineering",
      "degree_level": "Bachelor",
      "language": "Chinese",
      "duration": "4 Years",
      "city_province": "Shenyang, Liaoning",
      "tuition": "RMB 21,000 Per Year",
      "application_deadline": "Apr 30, 2027",
      "starting_date": "Sep 1, 2027",
      "scholarship_notes": "Scholarship service fee USD 200 if converting",
      "cucas_url": "https://neu.cucas.cn/program/Vehicle-Engineering-88085.html",
      "keyword_found": "Vehicle Engineering",
      "application_fee": "USD 71",
      "service_fee": "USD 100",
      "special_notes": "CSCA required; HSK5 180+; must pay RMB 21,000 tuition before admission letter; age 17+",
      "related_urls": [
        "https://neu.cucas.cn/program/Vehicle-Engineering-88085.html"
      ],
      "intake_notes": "Sep 1, 2027 / deadline Apr 30, 2027"
    },
    {
      "university": "Beihang University",
      "program_name": "Vehicle Engineering",
      "degree_level": "Bachelor",
      "language": "Chinese",
      "duration": "4 Years",
      "city_province": "Beijing",
      "tuition": "RMB 25,000 Per Year",
      "application_deadline": "Jun 30, 2026",
      "starting_date": "Sep 1, 2026",
      "scholarship_notes": "Scholarship service fee USD 200 if converting",
      "cucas_url": "https://buaa.cucas.cn/program/Vehicle-Engineering-74976.html",
      "keyword_found": "Vehicle Engineering",
      "application_fee": "USD 57",
      "service_fee": "USD 200",
      "special_notes": "CSCA required; HSK Level 5+ within 2 years; ages 18-22; senior high school diploma",
      "related_urls": [
        "https://buaa.cucas.cn/program/Vehicle-Engineering-74976.html"
      ],
      "intake_notes": "Sep 1, 2026 / deadline Jun 30, 2026"
    },
    {
      "university": "Tsinghua University",
      "program_name": "Vehicle Engineering (Automotive Design)",
      "degree_level": "Bachelor",
      "language": "Bilingual",
      "duration": "4 Years",
      "city_province": "Beijing",
      "tuition": "RMB 30,000 Per Year",
      "application_deadline": "Feb 28, 2027",
      "starting_date": "Sep 1, 2027",
      "scholarship_notes": "",
      "cucas_url": "https://thu.cucas.cn/program/Vehicle-Engineering--Automotive-Design--85186.html",
      "keyword_found": "Vehicle Engineering; Automotive Design",
      "application_fee": "USD 113",
      "service_fee": "USD 300",
      "special_notes": "CSCA required; HSK5 preferred (HSK4 accepted with upgrade to HSK5 in year 1); highly competitive; teaching language listed as Bilingual on CUCAS",
      "related_urls": [
        "https://thu.cucas.cn/program/Vehicle-Engineering--Automotive-Design--85186.html"
      ],
      "intake_notes": "Sep 1, 2027 / deadline Feb 28, 2027"
    },
    {
      "university": "Tongji University",
      "program_name": "Vehicle Engineering (College of Automotive Engineering)",
      "degree_level": "Bachelor",
      "language": "Chinese",
      "duration": "4 Years",
      "city_province": "Shanghai",
      "tuition": "RMB 24,600 Per Year",
      "application_deadline": "Apr 20, 2025",
      "starting_date": "Sep 1, 2025",
      "scholarship_notes": "",
      "cucas_url": "https://tongji.cucas.cn/program/Vehicle-Engineering-College-of-Automotive-Engineering--75696.html",
      "keyword_found": "Vehicle Engineering; Automotive Engineering",
      "application_fee": "USD 123",
      "service_fee": "USD 219",
      "special_notes": "HSK5 180+; listing dates appear stale (2025 intake still shown on CUCAS as of scrape); verify current cycle before applying",
      "related_urls": [
        "https://tongji.cucas.cn/program/Vehicle-Engineering-College-of-Automotive-Engineering--75696.html"
      ],
      "intake_notes": "Sep 1, 2025 / deadline Apr 20, 2025"
    },
    {
      "university": "Nanjing Institute of Technology",
      "program_name": "Vehicle Engineering",
      "degree_level": "Bachelor",
      "language": "Chinese",
      "duration": "4 Years",
      "city_province": "Nanjing, Jiangsu",
      "tuition": "RMB 16,000 Per Year",
      "application_deadline": "Jun 30, 2025",
      "starting_date": "Sep 1, 2025",
      "scholarship_notes": "Freshmen scholarship application form available on program page",
      "cucas_url": "https://njit.cucas.cn/program/Vehicle-Engineering-83444.html",
      "keyword_found": "Vehicle Engineering",
      "application_fee": "USD 103",
      "service_fee": "USD 54",
      "special_notes": "HSK4+; min 15 students to open class; online interview required; ages 18-28; listing dates may be stale (2025 shown)",
      "related_urls": [
        "https://njit.cucas.cn/program/Vehicle-Engineering-83444.html"
      ],
      "intake_notes": "Sep 1, 2025 / deadline Jun 30, 2025"
    },
    {
      "university": "Shenzhen Polytechnic University",
      "program_name": "New Energy Vehicle Engineering Technology",
      "degree_level": "Bachelor",
      "language": "Chinese",
      "duration": "4 Years",
      "city_province": "Shenzhen, Guangdong",
      "tuition": "RMB 29,000 Per Year",
      "application_deadline": "Jul 1, 2027",
      "starting_date": "Sep 1, 2027",
      "scholarship_notes": "",
      "cucas_url": "https://szpu.cucas.cn/program/New-Energy-Vehicle-Engineering-Technology-88784.html",
      "keyword_found": "New Energy Vehicle; NEV",
      "application_fee": "USD 57",
      "service_fee": "USD 202",
      "special_notes": "HSK4+; min 20 students; online interview; strong BYD / NEV industry collaboration; ages 18-under 30",
      "related_urls": [
        "https://szpu.cucas.cn/program/New-Energy-Vehicle-Engineering-Technology-88784.html"
      ],
      "intake_notes": "Sep 1, 2027 / deadline Jul 1, 2027"
    }
  ],
  "all_bachelor_listings": [
    {
      "university": "Chang'an University",
      "program_name": "Vehicle Engineering",
      "degree_level": "Bachelor",
      "language": "English",
      "duration": "4 Years",
      "city_province": "Xi'an, Shaanxi",
      "tuition": "RMB 16,000 Per Year",
      "application_deadline": "Jun 20, 2026",
      "starting_date": "Sep 1, 2026",
      "scholarship_notes": "CUCAS notes scholarship service fee USD 200 if converting to scholarship",
      "cucas_url": "https://chd.cucas.cn/program/Vehicle-Engineering-71881.html",
      "keyword_found": "Vehicle Engineering",
      "application_fee": "USD 57",
      "service_fee": "USD 200",
      "special_notes": "CSCA required; IELTS 5.5 / TOEFL IBT 68+; high school graduate; ages 18-50"
    },
    {
      "university": "Jiangsu University",
      "program_name": "Vehicle Engineering",
      "degree_level": "Bachelor",
      "language": "English",
      "duration": "4 Years",
      "city_province": "Zhenjiang, Jiangsu",
      "tuition": "RMB 20,000 Per Year",
      "application_deadline": "Jun 30, 2027",
      "starting_date": "Sep 14, 2027",
      "scholarship_notes": "JSU Presidential scholarship pages exist on CUCAS for Vehicle Engineering (Type A/B coverage noted on scholarship listing)",
      "cucas_url": "https://jsu.cucas.cn/program/Vehicle-Engineering-79482.html",
      "keyword_found": "Vehicle Engineering",
      "application_fee": "USD 29",
      "service_fee": "USD 200",
      "special_notes": "Autumn intake; CSCA required; IELTS 5.5+ / TOEFL 80+ / Duolingo 100+; RMB 3,000 deposit before admission letter; ages 18-25"
    },
    {
      "university": "Jiangsu University",
      "program_name": "Vehicle Engineering",
      "degree_level": "Bachelor",
      "language": "English",
      "duration": "4 Years",
      "city_province": "Zhenjiang, Jiangsu",
      "tuition": "RMB 20,000 Per Year",
      "application_deadline": "Jan 1, 2027",
      "starting_date": "Mar 13, 2027",
      "scholarship_notes": "JSU Presidential scholarship pages exist on CUCAS for Vehicle Engineering",
      "cucas_url": "https://jsu.cucas.cn/program/Vehicle-Engineering-72919.html",
      "keyword_found": "Vehicle Engineering",
      "application_fee": "USD 29",
      "service_fee": "USD 200",
      "special_notes": "Spring intake; CSCA required; IELTS 6.0+ / TOEFL 80+ / Duolingo 100+; RMB 3,000 deposit before admission letter; ages 18-25"
    },
    {
      "university": "Northeastern University",
      "program_name": "Vehicle Engineering",
      "degree_level": "Bachelor",
      "language": "Chinese",
      "duration": "4 Years",
      "city_province": "Shenyang, Liaoning",
      "tuition": "RMB 21,000 Per Year",
      "application_deadline": "Apr 30, 2027",
      "starting_date": "Sep 1, 2027",
      "scholarship_notes": "Scholarship service fee USD 200 if converting",
      "cucas_url": "https://neu.cucas.cn/program/Vehicle-Engineering-88085.html",
      "keyword_found": "Vehicle Engineering",
      "application_fee": "USD 71",
      "service_fee": "USD 100",
      "special_notes": "CSCA required; HSK5 180+; must pay RMB 21,000 tuition before admission letter; age 17+"
    },
    {
      "university": "Beihang University",
      "program_name": "Vehicle Engineering",
      "degree_level": "Bachelor",
      "language": "Chinese",
      "duration": "4 Years",
      "city_province": "Beijing",
      "tuition": "RMB 25,000 Per Year",
      "application_deadline": "Jun 30, 2026",
      "starting_date": "Sep 1, 2026",
      "scholarship_notes": "Scholarship service fee USD 200 if converting",
      "cucas_url": "https://buaa.cucas.cn/program/Vehicle-Engineering-74976.html",
      "keyword_found": "Vehicle Engineering",
      "application_fee": "USD 57",
      "service_fee": "USD 200",
      "special_notes": "CSCA required; HSK Level 5+ within 2 years; ages 18-22; senior high school diploma"
    },
    {
      "university": "Tsinghua University",
      "program_name": "Vehicle Engineering (Automotive Design)",
      "degree_level": "Bachelor",
      "language": "Bilingual",
      "duration": "4 Years",
      "city_province": "Beijing",
      "tuition": "RMB 30,000 Per Year",
      "application_deadline": "Feb 28, 2027",
      "starting_date": "Sep 1, 2027",
      "scholarship_notes": "",
      "cucas_url": "https://thu.cucas.cn/program/Vehicle-Engineering--Automotive-Design--85186.html",
      "keyword_found": "Vehicle Engineering; Automotive Design",
      "application_fee": "USD 113",
      "service_fee": "USD 300",
      "special_notes": "CSCA required; HSK5 preferred (HSK4 accepted with upgrade to HSK5 in year 1); highly competitive; teaching language listed as Bilingual on CUCAS"
    },
    {
      "university": "Tongji University",
      "program_name": "Vehicle Engineering (College of Automotive Engineering)",
      "degree_level": "Bachelor",
      "language": "Chinese",
      "duration": "4 Years",
      "city_province": "Shanghai",
      "tuition": "RMB 24,600 Per Year",
      "application_deadline": "Apr 20, 2025",
      "starting_date": "Sep 1, 2025",
      "scholarship_notes": "",
      "cucas_url": "https://tongji.cucas.cn/program/Vehicle-Engineering-College-of-Automotive-Engineering--75696.html",
      "keyword_found": "Vehicle Engineering; Automotive Engineering",
      "application_fee": "USD 123",
      "service_fee": "USD 219",
      "special_notes": "HSK5 180+; listing dates appear stale (2025 intake still shown on CUCAS as of scrape); verify current cycle before applying"
    },
    {
      "university": "Nanjing Institute of Technology",
      "program_name": "Vehicle Engineering",
      "degree_level": "Bachelor",
      "language": "Chinese",
      "duration": "4 Years",
      "city_province": "Nanjing, Jiangsu",
      "tuition": "RMB 16,000 Per Year",
      "application_deadline": "Jun 30, 2025",
      "starting_date": "Sep 1, 2025",
      "scholarship_notes": "Freshmen scholarship application form available on program page",
      "cucas_url": "https://njit.cucas.cn/program/Vehicle-Engineering-83444.html",
      "keyword_found": "Vehicle Engineering",
      "application_fee": "USD 103",
      "service_fee": "USD 54",
      "special_notes": "HSK4+; min 15 students to open class; online interview required; ages 18-28; listing dates may be stale (2025 shown)"
    },
    {
      "university": "Shenzhen Polytechnic University",
      "program_name": "New Energy Vehicle Engineering Technology",
      "degree_level": "Bachelor",
      "language": "Chinese",
      "duration": "4 Years",
      "city_province": "Shenzhen, Guangdong",
      "tuition": "RMB 29,000 Per Year",
      "application_deadline": "Jul 1, 2027",
      "starting_date": "Sep 1, 2027",
      "scholarship_notes": "",
      "cucas_url": "https://szpu.cucas.cn/program/New-Energy-Vehicle-Engineering-Technology-88784.html",
      "keyword_found": "New Energy Vehicle; NEV",
      "application_fee": "USD 57",
      "service_fee": "USD 202",
      "special_notes": "HSK4+; min 20 students; online interview; strong BYD / NEV industry collaboration; ages 18-under 30"
    }
  ],
  "excluded_non_bachelor": [
    {
      "university": "Jiangsu University",
      "program_name": "Vehicle Engineering(New Energy Vehicle Technology)",
      "degree_level": "Master",
      "language": "Chinese",
      "cucas_url": "https://jsu.cucas.cn/program/Vehicle-Engineering-New-Energy-Vehicle-Technology--76264.html",
      "reason": "Master (3 years); requires bachelor"
    },
    {
      "university": "Southwest Jiaotong University",
      "program_name": "Vehicle Engineering (School of Mechanical Engineering)",
      "degree_level": "Master",
      "language": "English",
      "cucas_url": "https://swjtu.cucas.cn/program/Vehicle-Engineering--School-of-Mechanical-Engineering--81865.html",
      "reason": "Master (3 years); English-taught"
    },
    {
      "university": "Tongji University",
      "program_name": "Vehicle Engineering(School of Automotive Studies)",
      "degree_level": "Master",
      "language": "Chinese",
      "cucas_url": "https://tongji.cucas.cn/program/Vehicle-Engineering-School-of-Automotive-Studies--85781.html",
      "reason": "Master (2.5 years)"
    },
    {
      "university": "Jiangsu University",
      "program_name": "Vehicle Engineering(Theory and Method of Vehicle System and Parts Design)-Automotive Engineering Research Institute",
      "degree_level": "Master (likely)",
      "language": "",
      "cucas_url": "https://jsu.cucas.cn/program/Vehicle-Engineering-Theory-and-Method-of-Vehicle-System-and-Parts-Design--Automotive-Engineering-Research-Institute-81477.html",
      "reason": "Discovered via Google; research-institute framing strongly indicates postgraduate; not fully verified as bachelor"
    },
    {
      "university": "Chang'an University",
      "program_name": "Vehicle Engineering",
      "degree_level": "Master",
      "language": "English",
      "cucas_url": "https://chd.cucas.cn/program/Vehicle-Engineering-61908.html",
      "reason": "Master (3 years); requires bachelor diploma"
    }
  ],
  "keywords_attempted": [
    "Vehicle Engineering",
    "Automobile Engineering",
    "Automotive Engineering",
    "Automotive Service Engineering",
    "Vehicle Operation Engineering",
    "Automotive Electronics",
    "New Energy Vehicle",
    "NEV",
    "Intelligent Vehicle",
    "Connected Vehicle",
    "车辆工程",
    "汽车工程",
    "新能源汽车"
  ],
  "blockers": [
    "www.cucas.cn/index/search returns JS anti-bot cookie challenge (arg1) to plain fetch and box Chrome; Apify web-fetch unblocker also returned challenge blob for search and studyinchina/programs",
    "apify/web-scraper and apify/puppeteer-scraper require account permission approval (console approvePermissions) — not runnable in this session",
    "cucas.edu.cn TLS/name issues from box; bachelor.cucas.cn DNS NXDOMAIN from box (linked from CUCAS pages but unresolved here)",
    "Apify free plan concurrent actor run limit (5) slowed bulk detail fetching",
    "Site search pagination could not be walked because search results never rendered past challenge"
  ],
  "method": [
    "Apify MCP apify/web-fetch (unblocker) for many *.cucas.cn/program detail pages",
    "Apify MCP apify/rag-web-browser Google discovery site:cucas.cn/program for automotive keywords",
    "Cursor WebFetch/WebSearch fallback for detail pages when Apify concurrency saturated",
    "Local Chrome/puppeteer attempted for search — failed Verification/arg1 challenge",
    "Degree filter applied by reading Bachelor vs Master markers on detail pages"
  ]
};
